#!/usr/bin/env php
<?php
if( php_sapi_name() !== 'cli' )
    die("Meant to be run from command line" . PHP_EOL);

define('WPMU_PLUGIN_URL', '/mu-plugins');
define('TR_GALAXY', true);

require __DIR__ . '/init.php';

if(is_file(TR_PATH . '/wordpress/wp-content/mu-plugins/typerocket.php'))
    define('TR_ROOT_INSTALL', true);

new \TypeRocket\Console\Launcher();
